{
 "title": "Intel Cluster Node Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostlist",
    "label": "Node",
    "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\")\r\n  |> group()\r\n  |> distinct(column: \"host\")\r\n  "
   },
   {
    "name": "timeinterval",
    "label": "Graph Interval",
    "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> group()\r\n  |> elapsed(unit: 1s)\r\n  |>sum(column:\"elapsed\")\r\n  |> map(\r\n        fn: (r) => ({\r\n            elapse: r.elapsed,\r\n            duration: \r\n            if r.elapsed < 600.00 then \"30s\" \r\n            else if r.elapsed > 600.00 and r.elapsed < 3600.00 then \"1m\"\r\n            else if r.elapsed > 3600.00 and r.elapsed < 86400.00 then \"15m\"\r\n            else if r.elapsed > 86400.00 and r.elapsed < 259200.00 then \"1h\"\r\n            else if r.elapsed > 259200.00 and r.elapsed < 432000.00 then \"3h\"\r\n            else \"6h\",\r\n           }),\r\n    )\r\n  |>drop(columns:[\"elapse\"])"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] > 98.00)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
    },
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] < 98.00 and r[\"_value\"] > 1.00)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
    },
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] <= 1)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used_percent\" or r[\"_measurement\"] == \"mem_total\")\r\n  |> toFloat()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({host:r.host,_value: r.mem_total * (r.mem_used_percent/100.00), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> mean()"
    },
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_available_percent\" or r[\"_measurement\"] == \"mem_total\")\r\n  |> toFloat()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({host:r.host,_value: r.mem_total * (r.mem_available_percent/100.00), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> mean()"
    },
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_available_percent\" or r[\"_measurement\"] == \"mem_used_percent\" or r[\"_measurement\"] == \"mem_total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> toFloat()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({host:r.host,_value: (100.00 - (r.mem_used_percent + r.mem_available_percent)) / 100.00 * r.mem_total, _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "CPU and Memory Power Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\" or r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> group(columns:[\"host\"])\r\n  |> keep(columns:[\"host\",\"_value\"])\r\n  |> sum()\r\n  "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spend On Idle",
     "type": "stat",
     "description": "Time Spent by host being more than 98% idle",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] > 98.00)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
      }
     ]
    },
    {
     "title": "Time Spend On Running",
     "type": "stat",
     "description": "Time Spent by host being more than 1% but less 98% idle",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] < 98.00 and r[\"_value\"] > 1.00)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
      }
     ]
    },
    {
     "title": "Time Spend On Busy",
     "type": "stat",
     "description": "Time Spent by host being less than 1% idle",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> drop(columns: [\"cpu\"])\r\n  |> group(columns: [\"host\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> elapsed(unit: 1s)\r\n  |> filter(fn: (r) => r[\"_value\"] <= 1)\r\n  |> map(fn: (r) => ({host:r.host,_value: float(v: r.elapsed), _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |> sum()\r\n  "
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu_usage_idle\" and r.cpu== \"cpu-total\"\r\n  )\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> map(fn: (r) => ({host:r.host,_value: 100.0 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu_usage_idle\" and r.cpu== \"cpu-total\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: 100.0 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Current Utilization of each logical core",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket:\"intel\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n          |> last()\r\n          |> map(fn: (r) => ({hostcpu: strings.joinStr(arr: [r.host,r.cpu ], v: \"-\"),_value: 100.00 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n          |> group(columns: [\"hostcpu\"])\r\n          |> pivot(rowKey: [\"_time\"], columnKey: [\"hostcpu\"], valueColumn: \"_value\")\r\n"
      }
     ]
    },
    {
     "title": "Utilization of each logical core",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket:\"intel\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n          |> sort(columns: [\"host\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(fn: (r) => ({hostcpu: strings.joinStr(arr: [r.host,r.cpu ], v: \"-\"),_value: 100.00 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n          |> group(columns: [\"hostcpu\"])\r\n          |> pivot(rowKey: [\"_time\"], columnKey: [\"hostcpu\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Current Each logical core Speed",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket:\"intel\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n          |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n          |> sort(columns: [\"host\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(fn: (r) => ({hostcpu: strings.joinStr(arr: [r.host,r.cpu_id ], v: \"-\"),_value: r._value * 1000000.00, _time: r._time, _start: r._start, _stop:r._stop }))\r\n          |> group(columns: [\"hostcpu\"])\r\n          |> pivot(rowKey: [\"_time\"], columnKey: [\"hostcpu\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Each logical core Speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket:\"intel\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n          |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n          |> sort(columns: [\"host\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(fn: (r) => ({hostcpu: strings.joinStr(arr: [r.host,r.cpu_id ], v: \"-\"),_value: r._value * 1000000.00, _time: r._time, _start: r._start, _stop:r._stop }))\r\n          |> group(columns: [\"hostcpu\"])\r\n          |> pivot(rowKey: [\"_time\"], columnKey: [\"hostcpu\"], valueColumn: \"_value\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Available Memory",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_available\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)"
      }
     ]
    },
    {
     "title": "Average Used Memory",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)"
      }
     ]
    },
    {
     "title": "Current Memory Usage %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> last()\r\n  |> sort(columns: [\"_time\"])\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Memory Usage %",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used_percent\")  \r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Current Memory Usage Bytes",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> sort(columns: [\"_time\"])\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Memory Usage Byte",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used\")  \r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current CPU Power Consumption",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "CPU Power Consumption",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Current Memory Power Consumption",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\")\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "Memory Power Consumption",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 20, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Integrated GPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current i915 GPU Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_render3d\"\r\n  )\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n   |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    },
    {
     "title": "i915 GPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 20, "x": 4, "y": 20 },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_render3d\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      },
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_video\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      },
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_blitter\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      },
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_video_enhance\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Packets Received",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"net_packets_recv\" and (r.interface == \"eno1\" or r.interface == \"enp3s0\")\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n"
      }
     ]
    },
    {
     "title": "Network Packets Sent",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"net_packets_sent\" and r.interface == \"eno1\"\r\n  )\r\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostlist:regex}$/)\r\n  |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
      }
     ]
    }
   ]
  }
 ]
}