# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-iaas-platform.fullname" . }}
  labels:
    {{- include "edge-iaas-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: http
  selector:
    {{- include "edge-iaas-platform.selectorLabels" . | nindent 4 }}
