apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-powerstat
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/sys/devices/virtual/powercap/intel-rapl"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-powerstat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
