apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-ras
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/rasdaemon"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-ras
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
