apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-rdt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/local/bin/pqos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-rdt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
