apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-pmu
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/pmu-events"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-pmu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
