apiVersion: v1
kind: Service
metadata:
  name: intel-influxdb2-nodeport-insecure
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8086
      nodePort: 32701
      protocol: TCP
      name: intel-influxdb2-nodeport-insecure
  selector:
    app.kubernetes.io/instance: intel-influxdb2
    app.kubernetes.io/name: influxdb2

