apiVersion: v1
kind: PersistentVolume
metadata:
  name: intel-influxdb-persistent-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/influxdbstorage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intel-influxdb2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
