apiVersion: v1
kind: Service
metadata:
  name: intel-grafana-nodeport-insecure
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32601
      protocol: TCP
      name: intel-grafana-nodeport-insecure
  selector:
    app.kubernetes.io/instance: intel-grafana
    app.kubernetes.io/name: grafana

