apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-dpdk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/dpdk/rte"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-dpdk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
